export const TOP_STORIES_REQUEST = '@stories/TOP_STORIES_REQUEST';
export const TOP_STORIES_SUCCESS = '@stories/TOP_STORIES_SUCCESS';
export const TOP_STORIES_FAILURE = '@stories/TOP_STORIES_FAILURE';

export const TOP_STORIES_UPDATES = '@stories/TOP_STORIES_UPDATES';

export const LOAD_STORIES_REQUEST = '@stories/LOAD_STORIES_REQUEST';
export const LOAD_STORIES_SUCCESS = '@stories/LOAD_STORIES_SUCCESS';
export const LOAD_STORIES_FAILURE = '@stories/LOAD_STORIES_FAILURE';
